freebsd_instance:
  image_family: freebsd-12-2

env:
  HOME: /home/username
  PATH: /usr/local/bin:$HOME/.local/bin:${PATH}

task:
  install_script:
    - mkdir -p $HOME
    - pkg upgrade -y
    - MAJ=`python -c "import sys;print(sys.version_info.major)"`
    - MIN=`python -c "import sys;print(sys.version_info.minor)"`
    - PY="py$MAJ$MIN"  # py39
    - PYV="$MAJ.$MIN"  # 3.9
    - pkg install -y curl python3 "$PY"-pip "$PY"-virtualenv "$PY"-docutils "$PY"-sqlite3 "$PY"-pytest "$PY"-coverage "$PY"-pytest-mock "$PY"-toml "$PY"-click "$PY"-blessed "$PY"-intspan
    - curl -sSL https://install.python-poetry.org | python"$PYV -
    - pip-"$PYV install pyfakefs
    - pwd
    - echo $PATH
    - /home/username/.local/bin/poetry --version
    - /home/username/.local/bin/poetry install
  test_script:
    - /home/username/.local/bin/poetry run coverage run --source=microlib -m pytest -vv
