stages:          # List of stages for jobs, and their order of execution
  - build

variables:
  POETRY: /root/.local/bin/poetry
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"

default:
  before_script:
    - apt -qq update
    - apt install -y python3-venv python3-pip curl

build:focal:
  stage: build
  image: ubuntu:focal
  cache:
      paths:
        - .cache/pip
        - .cache/pypoetry
        - $CI_PROJECT_DIR
  script:
    - apt install python-is-python3
    - pip3 install coveralls
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
    - $POETRY install
    - $POETRY run coverage run --source=microlib -m pytest -vv
    - coveralls

build:bionic:
  stage: build
  image: ubuntu:bionic
  variables:
    PYTHONIOENCODING: utf-8
  cache:
      paths:
        - .cache/pip
        - .cache/pypoetry
        - $CI_PROJECT_DIR
  script:
    - alias python="python3.6"
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
    - $POETRY install
    - $POETRY run pytest -vv
