stages:          # List of stages for jobs, and their order of execution
  - build

variables:
  POETRY: /root/.local/bin/poetry

default:
  before_script:
    - apt -qq update
    - apt install -y python3-venv python3-pip curl

build:focal:
  stage: build
  image: ubuntu:focal
  script:
    - apt install python-is-python3
    - pip3 install coveralls
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
    - $POETRY install
    - $POETRY run coverage run --source=microlib -m pytest -vv
    # - $POETRY run coveralls
    # - coveralls
# merge_test:   stage: test   script: make test-coveralls   only:   - merge_requests

build:bionic:
  stage: build
  image: ubuntu:bionic
  variables:
    PYTHONIOENCODING: utf-8
  script:
    - alias python="python3.6"
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
    - $POETRY install
