# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='microlib',
    version='1.1.0',
    python_requires='==3.*,>=3.6.0',
    author='Nicolas Hainaux',
    author_email='nh.techn@gmail.com',
    packages=['microlib'],
    package_dir={"": "."},
    package_data={"microlib": ["data/*.json", "data/*.toml", "meta/*.toml"]},
    install_requires=[
        'importlib-metadata==3.*,>=3.1.0; python_version == "3.6.*" or python_version == "3.7.*"',
        'toml==0.*,>=0.10.2'
    ],
    extras_require={
        "dev": [
            "coverage==5.*,>=5.3.0", "coveralls==2.*,>=2.2.0",
            "flake8==3.*,>=3.8.4", "pytest==5.*,>=5.2.0",
            "pytest-mock==3.*,>=3.3.1"
        ]
    },
)
